version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: dockerfiles/bot.docker
    links:
      - api
      - max
  api:
    build:
      context: .
      dockerfile: dockerfiles/api.docker
    env_file:
      - config/api.env
    links:
      - database

  database:
    image: postgres
    environment:
      - "POSTGRES_USER=salbot"
      - "POSTGRES_PASSWORD=salbot"
      - "POSTGRES_DB=salbot"

  max:
    build:
      context: .
      dockerfile: dockerfiles/max.docker